device = cuda
  0%|          | 0/10 [00:00<?, ?it/s]  0%|          | 0/10 [00:08<?, ?it/s]
torch.Size([60480, 8, 16])
dict_keys(['node1', 'node2', 'node3', 'node4', 'node5'])
torch.Size([60480, 128])
Traceback (most recent call last):
  File "/project/p_gnn001/code/tsp/tsp/train2.py", line 328, in <module>
    main()
  File "/project/p_gnn001/code/tsp/tsp/train2.py", line 321, in main
    val_loss = run(args)
               ^^^^^^^^^
  File "/project/p_gnn001/code/tsp/tsp/train2.py", line 213, in run
    epoch_loss = train(model, train_loader, args.target, criterion, optimizer, device)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/p_gnn001/code/tsp/tsp/train2.py", line 50, in train
    y_pred = model(batch, x)
             ^^^^^^^^^^^^^^^
  File "/home/p_gnngw/miniconda3/envs/cuda118/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/p_gnngw/miniconda3/envs/cuda118/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/p_gnn001/code/tsp/tsp/gnngls/models.py", line 173, in forward
    print(h[self.rel_names[0]].shape)
          ~^^^^^^^^^^^^^^^^^^^
KeyError: 'ss'
