tensor([[ 0,  1],
        [ 0,  2],
        [ 0,  3],
        ...,
        [63, 60],
        [63, 61],
        [63, 62]])
tensor([[ 0,  1],
        [ 0,  2],
        [ 0,  3],
        ...,
        [63, 60],
        [63, 61],
        [63, 62]])
device = cuda
  0%|          | 0/10 [00:00<?, ?it/s]  0%|          | 0/10 [01:44<?, ?it/s]
Traceback (most recent call last):
  File "/project/p_gnn001/code/tsp/tsp/train2.py", line 322, in <module>
    main()
  File "/project/p_gnn001/code/tsp/tsp/train2.py", line 315, in main
    val_loss = run(args)
               ^^^^^^^^^
  File "/project/p_gnn001/code/tsp/tsp/train2.py", line 225, in run
    es = H.ndata['e'].cpu().numpy()
         ~~~~~~~^^^^^
  File "/home/p_gnngw/miniconda3/envs/cuda118/lib/python3.12/site-packages/dgl/view.py", line 80, in __getitem__
    return self._graph._get_n_repr(self._ntid, self._nodes)[key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/p_gnngw/miniconda3/envs/cuda118/lib/python3.12/site-packages/dgl/frame.py", line 688, in __getitem__
    return self._columns[name].data
           ~~~~~~~~~~~~~^^^^^^
KeyError: 'e'
